version: "3.9"

services:
  app:
    build: 
      context: .  # Path to the Dockerfile
      args:
        - DEV=true
    image: recipe-app:latest  # Name of the Docker image
    container_name: recipe-app  # Name of the container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"